print("enter your personal information")#input unit
print("Name",end=" ")
name=input()
print("surname",end=" ")
surname=input()
print("phone number",end=" ")
phone=input()
print("street name",end=" ")
street=input()
print("house number",end=" ")
house=input()
print("apartment number",end=" ")
apartment=input()
print("city",end=" ")
city=input()
print("index",end=" ")
index=input()
print("country",end=" ")
country=input()
print("your result")#output unit
print(name," ",surname)
print(phone)
print("Str.",street," ",house,"ap.",apartment,",",city)
print(index)
print(country)